[colors.bright]
black = "#262626"
red = "#FF9999"
yellow = "#FFCC99"
green = "#FFFF99"
blue = "#99CCFF"
magenta = "#FF99CC"
cyan = "#99FFFF"
white = "#E5E5E5"

[colors.normal]
black = "#0C0C0C"
red = "#FF6565"
yellow = "#FFB265"
green = "#FFFF65"
blue = "#65B2FF"
magenta = "#FF65B2"
cyan = "#65FFFF"
white = "#D8D8D8"

[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

[font]
size = 10.0

[font.bold]
family = "Fira Code Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Fira Code Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Fira Code Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Fira Code Nerd Font Mono"
style = "Regular"

[window]
opacity = 1
blur = false
