[colors.bright]
black = "#262626"
red = "#ff9999"
yellow = "#ffcc99"
green = "#ffff99"
blue = "#99ccff"
magenta = "#ff99cc"
cyan = "#99ffff"
white = "#e6e6e6"

[colors.normal]
black = "#1a1a1a"
red = "#e65c5c"
yellow = "#e6a15c"
green = "#e6e65c"
blue = "#5ca1e6"
magenta = "#e65ca1"
cyan = "#5ce6e5"
white = "#f2f2f2"

[colors.primary]
background = "#0d0d0d"
foreground = "#ffffff"

[font]
size = 10.0

[font.bold]
family = "Fira Code Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Fira Code Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Fira Code Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Fira Code Nerd Font Mono"
style = "Regular"

[window]
opacity = 1
blur = false
