[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

[colors.bright]
black = "#262626"
white = "#F2F2F2"
red = "#FFCCCC"
yellow = "#FFF2CC"
green = "#F2FFCC"
cyan = "#CCF2FF"
blue = "#CCCCFF"
magenta = "#FFCCF2"

[colors.normal]
black = "#1A1A1A"
white = "#E6E6E6"
red = "#FF9999"
yellow = "#FFE699"
green = "#E6FF99"
cyan = "#99E6FF"
blue = "#9999FF"
magenta = "#FF99E6"

[colors.search.focused_match]
foreground = "#0D0D0D"
background = "#FFCCCC"

[colors.search.matches]
foreground = "#0D0D0D"
background = "#FFF2CC"

[colors.selection]
text = "#0D0D0D"
background = "#FFF2CC"

[colors.footer_bar]
foreground = "#0D0D0D"
background = "#FFF2CC"

[font]
size = 10.0

[font.bold]
family = "Fira Code Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Fira Code Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Fira Code Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Fira Code Nerd Font Mono"
style = "Regular"
