[colors.bright]
black = "#262626"
red = "#FFCCCC"
yellow = "#FFE6CC"
green = "#FFFFCC"
blue = "#CCE5FF"
magenta = "#FFCCE6"
cyan = "#CCFFFF"
white = "#F2F2F2"

[colors.normal]
black = "#0D0D0D"
red = "#FF9999"
yellow = "#FFCC99"
green = "#FFFF99"
blue = "#99CCFF"
magenta = "#FF99CC"
cyan = "#99FFFF"
white = "#D9D9D9"

[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

[font]
size = 10.0

[font.bold]
family = "Fira Code Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Fira Code Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Fira Code Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Fira Code Nerd Font Mono"
style = "Regular"

[window]
opacity = 1
blur = false
