[colors.primary]
background = "#000000"
foreground = "#FFFFFF"

[colors.bright]
black = "#262626"
red = "#FFB2B2"
yellow = "#FFD8B2"
green = "#FFFFB2"
cyan = "#B2FFFF"
blue = "#B2D8FF"
magenta = "#FFB2D8"
white = "#F2F2F2"

[colors.normal]
black = "#0C0C0C"
red = "#FF7F7F"
yellow = "#FFBF7F"
green = "#FFFF7F"
cyan = "#7FFFFF"
blue = "#7FBFFF"
magenta = "#FF7FBF"
white = "#D8D8D8"

[colors.search.focused_match]
foreground = "#0C0C0C"
background = "#FFB2B2"

[colors.search.matches]
foreground = "#0C0C0C"
background = "#FFD8B2"

[colors.selection]
text = "#0C0C0C"
background = "#FFD8B2"

[colors.footer_bar]
foreground = "#0C0C0C"
background = "#FFD8B2"

[font]
size = 10.0

[font.bold]
family = "Fira Code Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Fira Code Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Fira Code Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Fira Code Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.75
blur = false
