"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
show_hidden = true
show_symlink = true
sort_by = "natural"
sort_sensitive = true
sort_dir_first = true
sort_translit = true
linemode = "permissions"

[preview]
tab_size = 4

[which]
sort_by = "key"
sort_sensitive = true
sort_dir_first = true
sort_translit = true
